# Generated by Django 5.1.6 on 2025-06-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_alter_subscriptionprice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='features',
            field=models.TextField(blank=True, help_text='Features for pricing seperated by, New Line', null=True),
        ),
    ]
