name: 1- Hello world github actions

on:
  workflow_dispatch:
  push: #git push
  branches:
    - main

jobs:
  helo:
    runs-on: ubuntu-latest
    steps:
      - name: Hello there
        run: echo "hello"